### ISSUE TITLE
Most tests (except listing devices and platforms) are failing

### ISSUE THREAD

**Issue by anuraagvaidya** [unbornchikken/NOOOCL#13]
What could possibly be the reason? Thanks for your help in advance :)
Here's the log:

```
CLBuffer
    1) can copy contents of two node.js buffer through OpenCL
    2) supports sub buffers
    3) supports mapping of host array

  CLContext
    4) should construct from a device
    5) should construct from type

  CLHost
    √ should return platforms and devices (38ms)

  CLImage2D
    6) should convert an image to grayscale

  CLKernel
    7) should enqueue NDRange kernels

  CLContext
    8) should build and get kernel from string source
    9) should fail by building a fucked up string source
    10) should support binaries

  NOOOCL
Please enable GC for unit tests.
    11) should call release on gc collect


  1 passing (12s)
  11 failing

  1) CLBuffer can copy contents of two node.js buffer through OpenCL:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous>  runnable.js:215:19

  2) CLBuffer supports sub buffers:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous>  runnable.js:215:19

  3) CLBuffer supports mapping of host array:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous>  runnable.js:215:19

  4) CLContext should construct from a device:
     CLError: OpenCL Error Code: -2 Type: CL_DEVICE_NOT_AVAILABLE
      at CL11.checkError cl11.js:712:19
      at CLContext1 clContext.js:64:8
      at new CLContext clContext.js:108:20
      at Context.<anonymous> contextTests.js:34:23
      at callFn runnable.js:315:21
      at Test.Runnable.run (\mocha\lib\runnable.js:308:7)
      at Runner.runTest (\mocha\lib\runner.js:422:10)
      at \mocha\lib\runner.js:533:12
      at next (\mocha\lib\runner.js:342:14)
      at \mocha\lib\runner.js:352:7
      at next (\mocha\lib\runner.js:284:14)
      at Immediate._onImmediate (\mocha\lib\runner.js:320:5)

  5) CLContext should construct from type:
     CLError: OpenCL Error Code: -2 Type: CL_DEVICE_NOT_AVAILABLE
      at CL11.checkError (\nooocl\lib\cl11.js:712:19)
      at CLContext2 (\nooocl\lib\clContext.js:89:8)
      at new CLContext (\nooocl\lib\clContext.js:105:20)
      at Context.<anonymous> (\nooocl\tests\contextTests.js:44:23)
      at callFn (\mocha\lib\runnable.js:315:21)
      at Test.Runnable.run (\mocha\lib\runnable.js:308:7)
      at Runner.runTest (\mocha\lib\runner.js:422:10)
      at \mocha\lib\runner.js:533:12
      at next (\mocha\lib\runner.js:342:14)
      at \mocha\lib\runner.js:352:7
      at next (\mocha\lib\runner.js:284:14)
      at Immediate._onImmediate (\mocha\lib\runner.js:320:5)

  6) CLImage2D should convert an image to grayscale:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous> (\mocha\lib\runnable.js:215:19)

  7) CLKernel should enqueue NDRange kernels:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous> (\mocha\lib\runnable.js:215:19)

  8) CLContext should build and get kernel from string source:
     TypeError: Cannot read property 'filter' of null
      at \nooocl\lib\clWrapper.js:280:26
      at CLProgram.CLWrapper._cached (\nooocl\lib\clWrapper.js:103:18)
      at CLProgram.CLWrapper._getStringInfo2 (\nooocl\lib\clWrapper.js:276:17)
      at CLProgram.getBuildOptions (\nooocl\lib\clProgram.js:253:17)
      at \nooocl\tests\programTests.js:22:40
      at testMethod (\nooocl\tests\testHelpers.js:18:20)
      at \nooocl\tests\testHelpers.js:27:24
      at tryCatcher (\nooocl\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (\nooocl\node_modules\bluebird\js\release\promise.js:503:31)
      at Promise._settlePromise (\nooocl\node_modules\bluebird\js\release\promise.js:560:18)
      at Promise._settlePromise0 (\nooocl\node_modules\bluebird\js\release\promise.js:605:10)
      at Promise._settlePromises (\nooocl\node_modules\bluebird\js\release\promise.js:684:18)
      at Async._drainQueue (\nooocl\node_modules\bluebird\js\release\async.js:126:16)
      at Async._drainQueues (\nooocl\node_modules\bluebird\js\release\async.js:136:10)
      at Immediate.Async.drainQueues [as _onImmediate] (\nooocl\node_modules\bluebird\js\release\async.js:16:14)

  9) CLContext should fail by building a fucked up string source:
     TypeError: Cannot read property 'filter' of null
      at \nooocl\lib\clWrapper.js:280:26
      at CLProgram.CLWrapper._cached (\nooocl\lib\clWrapper.js:103:18)
      at CLProgram.CLWrapper._getStringInfo2 (\nooocl\lib\clWrapper.js:276:17)
      at CLProgram.getBuildOptions (\nooocl\lib\clProgram.js:253:17)
      at \nooocl\tests\programTests.js:51:40
      at testMethod (\nooocl\tests\testHelpers.js:18:20)
      at \nooocl\tests\testHelpers.js:27:24
      at tryCatcher (\nooocl\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (\nooocl\node_modules\bluebird\js\release\promise.js:503:31)
      at Promise._settlePromise (\nooocl\node_modules\bluebird\js\release\promise.js:560:18)
      at Promise._settlePromise0 (\nooocl\node_modules\bluebird\js\release\promise.js:605:10)
      at Promise._settlePromises (\nooocl\node_modules\bluebird\js\release\promise.js:684:18)
      at Async._drainQueue (\nooocl\node_modules\bluebird\js\release\async.js:126:16)
      at Async._drainQueues (\nooocl\node_modules\bluebird\js\release\async.js:136:10)
      at Immediate.Async.drainQueues [as _onImmediate] (\nooocl\node_modules\bluebird\js\release\async.js:16:14)

  10) CLContext should support binaries:
     TypeError: Cannot read property 'filter' of null
      at \nooocl\lib\clWrapper.js:280:26
      at CLProgram.CLWrapper._cached (\nooocl\lib\clWrapper.js:103:18)
      at CLProgram.CLWrapper._getStringInfo2 (\nooocl\lib\clWrapper.js:276:17)
      at CLProgram.getBuildOptions (\nooocl\lib\clProgram.js:253:17)
      at \nooocl\tests\programTests.js:79:40
      at testMethod (\nooocl\tests\testHelpers.js:18:20)
      at \nooocl\tests\testHelpers.js:27:24
      at tryCatcher (\nooocl\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (\nooocl\node_modules\bluebird\js\release\promise.js:503:31)
      at Promise._settlePromise (\nooocl\node_modules\bluebird\js\release\promise.js:560:18)
      at Promise._settlePromise0 (\nooocl\node_modules\bluebird\js\release\promise.js:605:10)
      at Promise._settlePromises (\nooocl\node_modules\bluebird\js\release\promise.js:684:18)
      at Async._drainQueue (\nooocl\node_modules\bluebird\js\release\async.js:126:16)
      at Async._drainQueues (\nooocl\node_modules\bluebird\js\release\async.js:136:10)
      at Immediate.Async.drainQueues [as _onImmediate] (\nooocl\node_modules\bluebird\js\release\async.js:16:14)

  11) NOOOCL should call release on gc collect:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous> (\mocha\lib\runnable.js:215:19)
```

**Comment by anuraagvaidya** [comment]
The tests were on Intel CPU, with Intel OpenCL SDK and AMD APP SDK installed.

**Comment by unbornchikken** [comment]
I'm getting this when testing against the Intel GPU device. CPU runs fine. You can fine tune what runs in testHelpers.js. It seems Intel GPU device doesn't support program initialization from binary. I'll verify this at home with AMD and Nvidia GPUs later.

**Comment by anuraagvaidya** [comment]
Okay thanks! So, is there a way to get around this issue to get CLImage2D to work?

**Comment by anuraagvaidya** [comment]
I should mention that the vector addition example is working. Is that a signal that it might work for pixel array operations?

**Comment by anuraagvaidya** [comment]
I was successful in making image2d work by modifying the test. Looks great! For checking things quickly, I had to remove bluebird support temporarily. Thanks anyway! Great project!

**Comment by unbornchikken** [comment]
May you share your work with me? I'm gonna integrate your findings to the core, and hacks won't be required anymore. A Gist would be fine.

**Comment by anuraagvaidya** [comment]
Sure. Will add a gist and notify you.

**Comment by anuraagvaidya** [comment]
Here's a working example of grayscaling an image. All I had to do was to refactor the code.
You'll need `npm install pngjs2`

I'm working on more examples such as blur and NMS. Will share them as well.

**Comment by unbornchikken** [comment]
Actually it would be better if you can make a PR from your findings. What do you think?

**Comment by anuraagvaidya** [comment]
Okay, sure. I'll do that in a day.
